name: Check Spelling

on:
  push:
    branches: [ LSW, PYH, LKZ, TKM, LJE ]
  pull_request:
    branches: [ gh-pages ]
    paths:
    - '**.txt'
    - '**.md'

  workflow_dispatch:

jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Check Spelling (JS, Vue, HTML, Markdown, Text)
      uses: UnicornGlobal/spellcheck-github-actions@0.4.0
